[project]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "spanish-lidar"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python-pdal = ">=3.4.5,<4"
jupyterlab = ">=4.3.5,<5"
ipywidgets = ">=8.1.5,<9"
tqdm = ">=4.67.1,<5"
geopandas = ">=1.0.1,<2"
